### PR TITLE
[TEST, DOC] Benchmarks: first macro benchmarks

### LINKED ISSUE #102: [TEST] Add some benchmarks for iGenVar
We would like to add some of the benchmark results in our repo.

### PR DESCRIPTION
**Pull request by Irallia**
Resolves #102 

EDIT (07.06.2021): We will wait for some result curves, to add these aswell.

I update also the workflow:

iGenVar_Workflow

### CODE REVIEW

**Comment by Irallia** [comment]
Our very first plots:

2021-06-10_iGenVar_Precision_Recall-F1

2021-06-10_iGenVar_Precision_Recall-F1-multimatch

**Comment by Irallia** [comment]
hierarchical_clustering_cutoff results all
max_overlap results all
max_tol_inserted_length results all
max_var_length results all
min_var_length results all

**Comment by Irallia** [comment]
We could also ask, how many of the SVs are detected by the cigar string method and how many by the SA tag (split read method).

**Comment by Irallia** [comment]
hierarchical_clustering_cutoff results all
max_overlap results all
max_tol_inserted_length results all
max_var_length results all
min_var_length results all

**Review by joergi-w — APPROVED** [review]

**Pull request merged**
