### PR TITLE
update seqan to master to include the file positioning information.

### PR DESCRIPTION
**Pull request by joshuak94**
The current branch of seqan3 in our submodule doesn't contain the necessary code for the bamintervaltree.

### CODE REVIEW

**Comment by joshuak94** [comment]
@Irallia Any idea why updating seqan causes the argument_parser to try and parse all uint types as strings?

**Comment by Irallia** [comment]
> @Irallia Any idea why updating seqan causes the argument_parser to try and parse all uint types as strings?

@eseiler I remember, that we had to do some changes regarding to differences between linux and mac. But now the argument_parser expects std::strings instead of integers. Have we done another change in seqan3?

**Comment by joshuak94** [comment]
@Irallia I figured it out, it's because I'm updating the seqan submodule to the master branch, where the file seeking stuff is on. But the correct parsing for the argument parser is on the release branch. After the next merge everything should be fine.

**Comment by joshuak94** [comment]
@Irallia Okay, now it should be good to merge.

**Review by Irallia — APPROVED** [review]

**Pull request merged**
