### PR TITLE
[BENCHMARKS] Dataset comparison: vaquita LR

### PR DESCRIPTION
**Pull request by Irallia**
See plots and:

Input File | Vaquita LR | DUP as INS
:--------:|:-----------:|:------------:
L1 | f1:        0.5715092873790522 | f1:        0.5727805635991242
  || precision: 0.8955289951305887 | precision: 0.8975210270030988
  || recall:    0.41966600975002594 | recall:    0.42059952287107144
L2 | f1:        0.5570222895477169 | f1:        0.5571665584649786
  || precision: 0.9144954997631455 | precision: 0.9147323543344387
  || recall:    0.4004771289285344 | recall:    0.40058085260865056
L3 | f1:        0.03204672823427263 | f1:        0.03204672823427263
  || precision: 0.06704095112285337 | precision: 0.06704095112285337
  || recall:    0.021055907063582617 | recall:    0.021055907063582617
S1 | f1:        0.17119150348489875 | f1:        0.17656820444739463
  || precision: 0.12587241934696666 | precision: 0.12982576016399044
  || recall:    0.26750337101960375 | recall:    0.27590498910901357
S1L1 | f1:        0.26129732336628886 | f1:        0.265374041383302
  || precision: 0.2441860465116279 | precision: 0.2480165885322755
  || recall:    0.28098744943470594 | recall:    0.2853438439995851
S1L2 | f1:        0.23543895398200035 | f1:        0.24121242995415182
  || precision: 0.1992813510600072 | precision: 0.20416816385195832
  || recall:    0.2876257649621409 | recall: 0.29467897521004044
  
  
Bildschirmfoto 2022-08-04 um 14 36 45

### CODE REVIEW

**Comment by joshuak94** [comment]
@Irallia am I seeing that vaquita-LR performs that much *worse* when combining long and short reads?

**Comment by Irallia** [comment]
> @Irallia am I seeing that vaquita-LR performs that much _worse_ when combining long and short reads?

It performs relly bad with my S1 (short read) dataset, and just a bit better when adding the long reads. With the long reads allone its okayish.

**Comment by Irallia** [comment]
@joshuak94 here you see the long read results compared with other long read callers: https://github.com/seqan/iGenVar/pull/228

I also saw that Vaquita-LR does not call any Insertions?

**Review by joergi-w — APPROVED** [review]

**Comment by Irallia** [comment]
@joshuak94 Now the plot looks better:

results DEL_only

**Pull request merged**
